import json

stories = {
  "1": { "DEFAULT": "A republic is a form of government where the country is considered a 'public matter', not the private concern or property of rulers. The primary positions of power within a republic are attained through democracy or a mix of democracy with aristocracy or autocracy, rather than being unalterably occupied." },
  "2": { "DEFAULT": "The Constitution is the highest law in the United States. No other law can go against it. It establishes the system of government and protects the rights of the people." },
  "3": { "DEFAULT": "The Constitution creates the structure of the U.S. government. It sets up the three branches—Legislative, Executive, and Judicial—and lists their powers to ensure no single part becomes too powerful." },
  "4": { "DEFAULT": "The phrase 'We the People' reinforces the idea of self-government (or popular sovereignty). It means that the government receives its power from the people, not from a king or a select group." },
  "5": { "DEFAULT": "The Constitution can be changed through amendments. This allows the government to adapt to new times while keeping the core system stable. It is a difficult process to ensure changes are well-considered." },
  "6": { "DEFAULT": "The Bill of Rights is the first ten amendments to the Constitution. It lists specific freedoms (like speech and religion) that the government cannot take away from the people." },
  "7": { "DEFAULT": "There are 27 amendments to the Constitution. The first ten are the Bill of Rights (ratified in 1791), and the most recent one (regarding congressional salaries) was ratified in 1992." },
  "8": { "DEFAULT": "The Declaration of Independence, adopted on July 4, 1776, announced that the 13 American colonies were separating from Great Britain to form a new, free nation." },
  "9": { "DEFAULT": "The Declaration of Independence is the document that formally announced the separation of the colonies from British rule." },
  "10": { "DEFAULT": "Important ideas include 'Liberty' (freedom to live as one chooses within the law) and 'Equality' (all people have the same fundamental rights)." },
  "11": { "DEFAULT": "These famous words are found in the Declaration of Independence: 'We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.'" },
  "12": { "DEFAULT": "The U.S. has a capitalist (or free market) economy. This means that private individuals and businesses, rather than the government, make most decisions about what to produce, sell, and buy." },
  "13": { "DEFAULT": "The 'Rule of Law' means that everyone—citizens and leaders alike—must obey the law. No person or group is above the law, which ensures fairness and justice." },
  "14": { "DEFAULT": "The Constitution was influenced by earlier documents like the Magna Carta (limiting king's power) and the Iroquois Great Law of Peace (confederation of tribes), as well as Enlightenment ideas." },
  "15": { "DEFAULT": "We have three branches (Separation of Powers) and a system of Checks and Balances to prevent any one branch or person from becoming too powerful, protecting the people's liberty." },
  "16": { "DEFAULT": "The three branches are the Legislative (makes laws), Executive (enforces laws), and Judicial (interprets laws)." },
  "17": { "DEFAULT": "The President is the head of the Executive branch, responsible for carrying out and enforcing the laws written by Congress." },
  "18": { "DEFAULT": "Congress is the legislative branch of the federal government. Its main job is to write and pass federal laws." },
  "19": { "DEFAULT": "Congress is bicameral, meaning it has two parts: the Senate (100 members) and the House of Representatives (435 members)." },
  "20": { "DEFAULT": "Congress has specific powers listed in the Constitution, including the power to declare war, print money, and create an annual budget for the government." },
  "21": { "DEFAULT": "There are 100 U.S. Senators. Each of the 50 states elects exactly two senators, regardless of the state's population size." },
  "22": { "DEFAULT": "Senators serve for six years. The terms are staggered so that about one-third of the Senate is up for re-election every two years." },
  "23": { "DEFAULT": "Senators represent their entire state. You can find your current senators on the official Senate website senate.gov." },
  "24": { "DEFAULT": "The House of Representatives has 435 voting members. The number of representatives depends on the state's population." },
  "25": { "DEFAULT": "Representatives serve two-year terms. This short term is designed to make them very responsive to the changing opinions of the people in their district." },
  "26": { "DEFAULT": "Representatives have shorter terms (2 years) than Senators (6 years) so they must frequently go back to the voters, keeping them closer to public opinion." },
  "27": { "DEFAULT": "Each state has two Senators to ensure equal representation for every state in the Senate, balancing the power of large and small states." },
  "28": { "DEFAULT": "This system (the Great Compromise) was created so that small states wouldn't be overshadowed by large states. In the Senate, all states are equal." },
  "29": { "DEFAULT": "Your Representative depends on your specific congressional district. You can look this up at house.gov using your zip code." },
  "30": { "DEFAULT": "The Speaker of the House is the leader of the House of Representatives and matches the majority political party. They are second in line to the Presidency." },
  "31": { "DEFAULT": "A Senator represents all the people of their state, balancing the interests of the entire state's population." },
  "32": { "DEFAULT": "Originally, senators were chosen by state legislatures, but the 17th Amendment (1913) changed this to allow citizens of the state to elect them directly." },
  "33": { "DEFAULT": "A Representative represents the people living in their specific congressional district (a section of their state)." },
  "34": { "DEFAULT": "Citizens living in a specific congressional district elect their Representative." },
  "35": { "DEFAULT": "States with higher populations have more representatives in the House. This ensures that people in populous states have a proportionate voice in making laws." },
  "36": { "DEFAULT": "The President is elected for a four-year term. They can serve a maximum of two terms." },
  "37": { "DEFAULT": "The 22nd Amendment limits the president to two terms to preventing any one person from holding power for too long, protecting democracy (inspired by George Washington's example)." },
  "38": { "DEFAULT": "The current President is the head of state and head of government. Visit whitehouse.gov for the current officeholder." },
  "39": { "DEFAULT": "The current Vice President serves as the President of the Senate and is first in line to the presidency." },
  "40": { "DEFAULT": "If the President can no longer serve, the Vice President becomes President." },
  "41": { "DEFAULT": "If both the President and Vice President can no longer serve, the Speaker of the House becomes President." },
  "42": { "DEFAULT": "The President is the Commander in Chief, meaning they are the supreme commander of the nation's military forces." },
  "43": { "DEFAULT": "The President signs bills passed by Congress to update the law. A bill cannot become law without the President's signature (or a veto override)." },
  "44": { "DEFAULT": "The President can veto (reject) a bill passed by Congress. This is a check on the legislative branch." },
  "45": { "DEFAULT": "The President appoints federal judges, cabinet members, and ambassadors. The Senate must approve these appointments." },
  "46": { "DEFAULT": "The Cabinet advises the President on any subject relating to their respective offices (e.g., defense, treasury, education)." },
  "47": { "DEFAULT": "Cabinet-level positions include the Secretary of State, Secretary of Defense, Attorney General, and others." },
  "48": { "DEFAULT": "The Electoral College is the system used to elect the President. Each state gets a number of votes based on its population (Representatives + Senators)." },
  "49": { "DEFAULT": "The Judicial Branch interprets the law, decides if laws violate the Constitution, and resolves disputes." },
  "50": { "DEFAULT": "The Supreme Court is the highest court in the United States. Its decisions are final and apply to the entire country." },
  "51": { "DEFAULT": "There are nine justices on the Supreme Court: one Chief Justice and eight Associate Justices." },
  "52": { "DEFAULT": "Federal judges serve for life (meaning until they die, retire, or are removed) to protect them from political pressure." },
  "53": { "DEFAULT": "The current Chief Justice presides over the Supreme Court. Visit supremecourt.gov for the current list of justices." },
  "54": { "DEFAULT": "The federal government has powers like printing money, declaring war, and creating an army. These are enumerated powers." },
  "55": { "DEFAULT": "Powers not given to the federal government belong to the states (reserved powers). These include issuing driver's licenses and schooling." },
  "56": { "DEFAULT": "The Governor is the head of the executive branch of a state government." },
  "57": { "DEFAULT": "The capital of your state is where the state government meets." },
  "58": { "DEFAULT": "Political parties help organize groups of people with similar ideas to elect candidates. The two major parties are Democratic and Republican." },
  "59": { "DEFAULT": "The Democratic Party and the Republican Party are the two major political parties in the U.S. today." },
  "60": { "DEFAULT": "The political party of the current President typically shapes the policies of the Executive branch." },
  "61": { "DEFAULT": "Citizens participate in democracy by voting, joining political parties, running for office, or publicly supporting issues." },
  "62": { "DEFAULT": "April 15 is the deadline for filing federal income tax returns." },
  "63": { "DEFAULT": "All men aged 18-25 must register for the Selective Service. This allows the government to draft men in a national emergency." },
  "64": { "DEFAULT": "Colonists came to America for freedom of religion, economic opportunity, and political liberty." },
  "65": { "DEFAULT": "Native Americans lived in America before the Europeans arrived. There were many diverse tribes with their own cultures." },
  "66": { "DEFAULT": "Africans were taken to America and sold as slaves. This practice continued until the Civil War ended it." },
  "67": { "DEFAULT": "The colonists fought the British because of high taxes (taxation without representation), quartering of soldiers, and lack of self-government." },
  "68": { "DEFAULT": "Thomas Jefferson was the main author of the Declaration of Independence." },
  "69": { "DEFAULT": "The Declaration of Independence was adopted on July 4, 1776, marking the birth of the United States." },
  "70": { "DEFAULT": "The original 13 states included New York, Virginia, Massachusetts, and Pennsylvania." },
  "71": { "DEFAULT": "The Constitutional Convention was held in 1787 to write the Constitution." },
  "72": { "DEFAULT": "The Federalist Papers supported the passage of the U.S. Constitution. Writers included Alexander Hamilton, James Madison, and John Jay." },
  "73": { "DEFAULT": "Benjamin Franklin was a diplomat, inventor, and writer. He started the first free libraries." },
  "74": { "DEFAULT": "George Washington is called the 'Father of Our Country' because he was the first President." },
  "75": { "DEFAULT": "George Washington was the first President of the United States." },
  "76": { "DEFAULT": "The Louisiana Purchase (1803) doubled the size of the United States. It was bought from France." },
  "77": { "DEFAULT": "The U.S. fought the War of 1812, the Mexican-American War, the Civil War, and the Spanish-American War in the 1800s." },
  "78": { "DEFAULT": "The Civil War was fought between the North (Union) and the South (Confederacy) from 1861 to 1865." },
  "79": { "DEFAULT": "The Civil War was caused by slavery, economic reasons, and states' rights." },
  "80": { "DEFAULT": "Abraham Lincoln led the country during the Civil War and issued the Emancipation Proclamation." },
  "81": { "DEFAULT": "The Emancipation Proclamation freed slaves in the Confederacy (the Southern states rebelling against the Union)." },
  "82": { "DEFAULT": "Susan B. Anthony fought for women's rights and civil rights." },
  "83": { "DEFAULT": "The U.S. fought in World War I, World War II, the Korean War, the Vietnam War, and the Persian Gulf War in the 1900s." },
  "84": { "DEFAULT": "Woodrow Wilson was President during World War I." },
  "85": { "DEFAULT": "Franklin D. Roosevelt was President during the Great Depression and World War II." },
  "86": { "DEFAULT": "The U.S. fought Japan, Germany, and Italy in World War II." },
  "87": { "DEFAULT": "Eisenhower was a general in World War II before becoming President." },
  "88": { "DEFAULT": "During the Cold War, the main concern of the United States was Communism." },
  "89": { "DEFAULT": "The Civil Rights Movement tried to end racial discrimination." },
  "90": { "DEFAULT": "Martin Luther King, Jr. fought for civil rights and worked for equality for all Americans." },
  "91": { "DEFAULT": "September 11, 2001 is when terrorists attacked the United States." },
  "92": { "DEFAULT": "American Indian tribes include Cherokee, Navajo, Sioux, and Chippewa." },
  "93": { "DEFAULT": "The Mississippi and Missouri Rivers are the two longest rivers in the United States." },
  "94": { "DEFAULT": "The Pacific Ocean is on the West Coast of the United States." },
  "95": { "DEFAULT": "The Atlantic Ocean is on the East Coast of the United States." },
  "96": { "DEFAULT": "U.S. Territories include Puerto Rico, Guam, and U.S. Virgin Islands." },
  "97": { "DEFAULT": "States bordering Canada include New York, Washington, and Michigan." },
  "98": { "DEFAULT": "States bordering Mexico include California, Arizona, New Mexico, and Texas." },
  "99": { "DEFAULT": "Washington, D.C. is the capital of the United States." },
  "100": { "DEFAULT": "The Statue of Liberty is in New York Harbor. It was a gift from France." },
  "101": { "DEFAULT": "The flag has 13 stripes to represent the original 13 colonies." },
  "102": { "DEFAULT": "The flag has 50 stars to represent the 50 states." },
  "103": { "DEFAULT": "The National Anthem is called 'The Star-Spangled Banner'." },
  "104": { "DEFAULT": "Independence Day is celebrated on July 4th." },
  "105": { "DEFAULT": "National holidays include Thanksgiving, Christmas, and Independence Day." },
  "106": { "DEFAULT": "The Constitution is the supreme law of the land." },
  "107": { "DEFAULT": "The first three words of the Constitution are 'We the People'." },
  "108": { "DEFAULT": "The 10th Amendment reserves powers not given to the federal government to the states or people." },
  "109": { "DEFAULT": "The 13th Amendment abolished slavery." },
  "110": { "DEFAULT": "The 14th Amendment guarantees citizenship to all persons born or naturalized in the U.S." },
  "111": { "DEFAULT": "The 15th Amendment prohibits denying the right to vote based on race." },
  "112": { "DEFAULT": "The 19th Amendment gave women the right to vote." },
  "113": { "DEFAULT": "The 24th Amendment abolished poll taxes." },
  "114": { "DEFAULT": "The 26th Amendment lowered the voting age to 18." },
  "115": { "DEFAULT": "Citizens must serve on a jury if called." },
  "116": { "DEFAULT": "Citizens must obey federal, state, and local laws." },
  "117": { "DEFAULT": "Male citizens aged 18-26 must register for Selective Service." },
  "118": { "DEFAULT": "The oath of allegiance is a promise to be loyal to the United States." },
  "119": { "DEFAULT": "Treason is the crime of betraying one's country." },
  "120": { "DEFAULT": "The Pledge of Allegiance is a promise of loyalty to the flag and the country." },
  "121": { "DEFAULT": "The flag has 13 stripes because there were 13 original colonies." },
  "122": { "DEFAULT": "The flag has 50 stars because there is one star for each state." },
  "123": { "DEFAULT": "The National Anthem is 'The Star-Spangled Banner'." },
  "124": { "DEFAULT": "'E Pluribus Unum' means 'Out of many, one'." },
  "125": { "DEFAULT": "Independence Day celebrates the adoption of the Declaration of Independence." },
  "126": { "DEFAULT": "National holidays include Memorial Day, Veterans Day, and President's Day." },
  "127": { "DEFAULT": "Memorial Day honors soldiers who died in military service." },
  "128": { "DEFAULT": "Veterans Day honors all those who have served in the U.S. military." }
}

with open("stories_data.json", "w") as f:
    json.dump(stories, f, indent=2)
